datafile="height"
stats datafile

set terminal png size 600,400

set xdata time
set timefmt "%s"
set format x "%Y-%m-%d"
set xtics rotate

set ylabel "Height"

set offsets 0, 0.1, 0, 0.1

set output "height.png"
set title "Height of The Boulder"
unset key

plot datafile using 1:2 pointtype 0 with linespoints
